name: Firebase Function Deploy
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Npm Packages
      run: |
        cd functions
        npm install
        cd ..
    - name: Create Env File
      run: |
        cd functions
        touch .env
        echo API_TOKEN=${{ secrets.API_TOKEN }} >> .env
        echo ENVIRONMENT=${{ secrets.ENVIRONMENT }} >> .env
        echo NODE_URL=${{ secrets.NODE_URL }} >> .env
    - name:  Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
          args: deploy --only functions:api
      env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}