name: Firebase Function Deploy
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Npm Packages
      run: |
        cd functions
        npm install
        cd ..
    - name: Create Env File
      run: |
        cd functions
        touch .env
        echo API_TOKEN=${{ secrets.API_TOKEN }} >> .env
        echo ENVIRONMENT=${{ secrets.ENVIRONMENT }} >> .env
        echo RINKEBY_NODE=${{ secrets.RINKEBY_NODE }} >> .env
        echo ROPSTEN_NODE=${{ secrets.ROPSTEN_NODE }} >> .env
        echo GOERLI_NODE=${{ secrets.GOERLI_NODE }} >> .env
        echo MAINNET_NODE=${{ secrets.MAINNET_NODE }} >> .env
        echo MUMBAI_NODE=${{ secrets.MUMBAI_NODE }} >> .env
    - name:  Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
          args: deploy --only functions:api
      env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}